services:
    _defaults:
        autowire: true
        autoconfigure: true


    numero2_inxmail.api.inxmail:
        class: numero2\InxmailBundle\API\InxmailApi
        public: true
        arguments:
            - '@http_client'
            - '@monolog.logger.contao.error'
